clusterGroup:
  name: hub
  isHubCluster: true
  storageClass: gp2

# Namespaces that are expected to be created.
# The pattern will apply these namespaces
# and creates an operator group for that namespace
  namespaces:
  - open-cluster-management
  - vault
  - golang-external-secrets
  - rhacs-operator
  - stackrox
  - policies
  - devsecops-ci
  - openshift-storage
  - quay-enterprise

#  subscriptions:  OpenShift Operator subscriptions from OLM/OperatorHub
#  - name: the Operator package name (required)
#    namespace: expected namespace as specified by Operator (defaults to openshift-operators)
#    channel: operator channel from package manifest (required)
#    csv: Operator CSV from package manifest.
#         only used if global.options.useCSV: true in values-global.yaml

  subscriptions:
    advanced-cluster-management:
      name: advanced-cluster-management
      namespace: open-cluster-management

    rhacs-operator:
      name: rhacs-operator  #packageName
      namespace: openshift-operators # operator namespace

    odf-operator:
      name: odf-operator
      namespace: openshift-storage

    quay-operator:
      name: quay-operator
      namespace: openshift-operators

# The following section is used by
# OpenShift GitOps (ArgoCD)
  projects:
  - hub
  - opp
  - golang-external-secrets

  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml' #   E:

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: opp
      chart: acm
      chartVersion: 0.1.*
      ignoreDifferences:
        - group: internal.open-cluster-management.io
          kind: ManagedClusterInfo
          jsonPointers:
            - /spec/loggingCA

    opp:
      name: opp
      namespace: openshift
      project: opp
      path: charts/hub/opp

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    cli-tools:
      name: cli-tools
      namespace: openshift
      project: hub
      path: charts/hub/cli-tools

# This section is used by ACM
  managedClusterGroups:
  - name: devel
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
      matchLabels:
        clusterGroup: devel
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

  - name: secured
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
      matchLabels:
        clusterGroup: secured
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

